### ISSUE TITLE
cumulative collaborating

### ISSUE THREAD

**Issue by jbytecode** [SevgiAkten/pycellga#56]
![Screenshot from 2024-08-12 12-44-48](https://github.com/user-attachments/assets/09c38680-a27a-4278-8685-630bc13bb1fc)

I think I should stop editing this repo, just because my commits have always been reverted and it seems you think I did something accidentally.

**Comment by jbytecode** [comment]
https://github.com/SevgiAkten/pycellga/blob/c60f89deeea561ae755f1f02e498d4e548644906/src/individual.py#L116

In here, you already sample candidates using a probability vector.

**Comment by SevgiAkten** [comment]
I reintroduced it because it was used, but I realize now that the issue is likely due to my lack of comprehensive test coverage, and the error wasn’t caught because the tests passed. 
I will resolve this by writing more comprehensive test functions. 

Your contributions to the repository are extremely valuable, and your guidance is greatly enhancing its quality. Please continue making commits to this repository.
